name: Uso de Matrix
on:
  push:
    branches:
      - master
jobs:
  output:
    strategy:
      matrix:
        os: [ubuntu-latest,macos-latest]
        msj: ['Michel', 'Chilito']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Imprimiendo valores de matrix
        run: |
          echo ${{ matrix.os }}
          echo ${{ matrix.msj }}